apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: recommend-api-cert
  namespace: recommend-prod
spec:
  secretName: recommend-api-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - Recommended System
  commonName: api.recommend.com
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - api.recommend.com
    - www.api.recommend.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io

